In [3]:
import os
import torch
from torchvision.utils import save_image
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.sampler import RandomSampler, BatchSampler

class Generator(object):
    def __init__(self, n_frames):
        self.n_frames = n_frames
    
    def generate(self, folder_path, prefix=""):
        front, back = torch.randn(2, self.n_frames, 3, 64, 64)
        for t in range(self.n_frames):
            front_img = f"img_{t}_front.png"
            back_img = f"img_{t}_back.png"
            if prefix:
                front_img = f"{prefix}_img_{t}_front.png"
                back_img = f"{prefix}_img_{t}_back.png"
            save_image(front[t], os.path.join(folder_path, front_img))
            save_image(back[t], os.path.join(folder_path, back_img))

In [4]:
Generator(48).generate("./images/")

FileNotFoundError: [Errno 2] No such file or directory: './images/img_0_front.png'

In [5]:
class SynthDataset(Dataset):
    def __init__(self):
        self.data = torch.arange(100).view(100, 1).float()
        
    def __getitem__(self, index):
        x = self.data[index]
        print(x.shape)
        return x
    
    def __len__(self):
        return len(self.data)

dataset = SynthDataset()        
sampler = BatchSampler(
    RandomSampler(dataset),
    batch_size=10,
    drop_last=False)

loader = DataLoader(
    dataset,
    sampler=sampler)

for data in loader:
    print(data)

torch.Size([10, 1])
tensor([[[29.],
         [97.],
         [22.],
         [88.],
         [60.],
         [71.],
         [68.],
         [94.],
         [82.],
         [25.]]])
torch.Size([10, 1])
tensor([[[33.],
         [52.],
         [91.],
         [70.],
         [87.],
         [69.],
         [ 2.],
         [ 3.],
         [65.],
         [17.]]])
torch.Size([10, 1])
tensor([[[ 0.],
         [38.],
         [58.],
         [51.],
         [11.],
         [34.],
         [57.],
         [55.],
         [ 8.],
         [ 7.]]])
torch.Size([10, 1])
tensor([[[18.],
         [99.],
         [85.],
         [98.],
         [45.],
         [46.],
         [61.],
         [77.],
         [96.],
         [95.]]])
torch.Size([10, 1])
tensor([[[79.],
         [76.],
         [40.],
         [75.],
         [48.],
         [16.],
         [32.],
         [37.],
         [31.],
         [64.]]])
torch.Size([10, 1])
tensor([[[39.],
         [89.],
         [49.],
         [ 9.],
      